### ISSUE TITLE
[ICON REQUEST] - Banano

### ISSUE THREAD

**Issue by yekta** [0xa3k5/token-icons#46]
I tried adding these via a PR myself but I'm getting issues with `bun run add-icons` command so I figured I should just open an icon request. There are 2 sets of icons one for `BAN` one for `BANANO` unfortunately because some exchanges decided to give our ticker away to some other very new project. However, our ticker is still `BAN` on CMC. The SVGs are SVGO optimized and fitted to the icon grid you shared.

BAN - Branded
![BAN-branded](https://github.com/user-attachments/assets/75971b43-d1e7-4dca-b7f4-f14c9de5bd74)

BAN - Mono
![BAN-mono](https://github.com/user-attachments/assets/fc370464-0af7-4a53-8ecf-e6139a1d3336)

BANANO - Branded
![BANANO-branded](https://github.com/user-attachments/assets/8d3c8e06-7675-41ef-9cd2-e7f2cf1eb6ff)

BANANO - Mono
![BANANO-mono](https://github.com/user-attachments/assets/fdd42f4a-a780-4bee-9254-4964c614eef6)

Here is the project home page for reference: https://banano.cc. Banano has been active since 2018.

**Comment by 0xa3k5** [comment]
ah, seems like for some reason inquirer is failing. I've seen this before, will try to replace that too. Thank you!
